### PR TITLE
callback state as buffers

### PR DESCRIPTION
**Pull request by m4gpi**
Resolving the same issue for when using level, as kappa-view-list: https://github.com/kappa-db/kappa-view-list/pull/4

### CODE REVIEW

**Comment by m4gpi** [comment]
@noffle good to get a go-ahead on this! Its pretty minor.

**Comment by hackergrrl** [comment]
Nice fix. I have regrets this wasn't how it got done across all views :(
Now it'd mean a major bump that'd require everyone to regenerate their
views.

**Comment by hackergrrl** [comment]
Hey I noticed that `master` is currently passing. I pushed the commit
21e9256c1805945773aa07ecfb962fa3b6151f5b to master that changes the
tests to use level@5 and it's still passing. How did you reproduce the
bug?

**Comment by m4gpi** [comment]
I'm getting inconsistent behaviour with this. I'm not sure why this is... I'm going to see if I can reproduce the bug and I'll create a proper issue and reference it if I do, in the meantime, lets put this on hold.

**Comment by m4gpi** [comment]
> Nice fix. I have regrets this wasn't how it got done across all views :( Now it'd mean a major bump that'd require everyone to regenerate their views.
> […](#)
> On 08/28 07:25, Kieran Gibb wrote: @noffle good to get a go-ahead on this! -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#1 (comment)](https://github.com/kappa-db/kappa-view-kv/pull/1#issuecomment-525769601)

Ah thats frustrating!!

**Comment by hackergrrl** [comment]
Thanks for this! Sorry it took so long :3

**Pull request merged**
